2020-12-14 15:52:45,190 [DEBUG] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:939 [_new_conn] Starting new HTTPS connection (1): ipinfo.io:443
2020-12-14 15:52:45,604 [DEBUG] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:433 [_make_request] https://ipinfo.io:443 "GET /?token=26d03faada92e8 HTTP/1.1" 200 None
2020-12-14 15:52:46,318 [DEBUG] /home/luna/git/PyArchboot/modules/system_manager/unix_command.py:133 [command_output] Aucun volume lvm existant détecté
2020-12-14 15:52:46,348 [DEBUG] /home/luna/git/PyArchboot/modules/system_manager/unix_command.py:133 [command_output] Aucun volume luks existant détecté
2020-12-14 15:52:46,380 [DEBUG] /home/luna/git/PyArchboot/modules/system_manager/unix_command.py:133 [command_output] Aucun volume ntfs existant détecté
2020-12-14 15:52:46,386 [INFO] /home/luna/git/PyArchboot/modules/questioner/questions.py:53 [question_manager] utilisez les flèches du clavier pour sélectionner une option
2020-12-14 15:52:46,388 [WARNING] /home/luna/git/PyArchboot/modules/questioner/questions.py:54 [question_manager] toutes les données seront perdues !
